// <auto-generated />
using System;
using GastronomyApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GastronomyApp.Infrastructure.Migrations
{
    [DbContext(typeof(GastronomyAppDbContext))]
    partial class GastronomyAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("GastronomyApp.Core.Entities.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenAlgorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TokenIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenLookupId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("StaffMemberId")
                        .IsUnique();

                    b.HasIndex("TokenLookupId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.EnrolmentInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConsumedByDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IsOutstandingMarker")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("CASE WHEN ConsumedAtUtc IS NULL THEN 1 END", true);

                    b.Property<string>("QrCodeAlgorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("QrCodeHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("QrCodeIterations")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("QrCodeSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsOutstandingMarker")
                        .IsUnique();

                    b.ToTable("EnrolmentInvitations");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.ItemStationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId", "StationId")
                        .IsUnique();

                    b.ToTable("ItemStationAssignments");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GlobalOrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StationOrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationOrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CopyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailureReason")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrinterJobId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StationOrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationOrderId", "CopyNumber")
                        .IsUnique();

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Printer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Printers", (string)null);

                    b.HasDiscriminator<string>("PrinterType").HasValue("Printer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.PrinterStatus", b =>
                {
                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCoverOpen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFaulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInErrorState")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaperEnd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaperNearEnd")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDetail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeardFromAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("PrinterId");

                    b.ToTable("PrinterStatuses");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.SequenceCounters", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextOrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextPrinterJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SequenceCounters");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextStationOrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PrinterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.StationOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StationOrderNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("OrderId", "StationId")
                        .IsUnique();

                    b.ToTable("StationOrders");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.EpsonTmT20ivNetworkPrinter", b =>
                {
                    b.HasBaseType("GastronomyApp.Core.Entities.Printer");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("EpsonTmT20ivNetworkPrinter");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.TestPrinter", b =>
                {
                    b.HasBaseType("GastronomyApp.Core.Entities.Printer");

                    b.HasDiscriminator().HasValue("TestPrinter");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.StationOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("StationOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.PrintJob", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.StationOrder", null)
                        .WithMany("PrintJobs")
                        .HasForeignKey("StationOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Station", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.Printer", null)
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.StationOrder", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.Order", null)
                        .WithMany("StationOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastronomyApp.Core.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Order", b =>
                {
                    b.Navigation("StationOrders");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.StationOrder", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PrintJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
