// <auto-generated />
using System;
using GastronomyApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GastronomyApp.Infrastructure.Migrations
{
    [DbContext(typeof(GastronomyAppDbContext))]
    partial class GastronomyAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("GastronomyApp.Core.Entities.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenAlgorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TokenIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenLookupId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UserAgentSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenLookupId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.EnrolmentInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeAlgorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeIterations")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConsumedByDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedSixDigitAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IsOutstandingMarker")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("CASE WHEN ConsumedAtUtc IS NULL THEN 1 END", true);

                    b.Property<byte[]>("QrCodeHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("QrCodeSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("ServerPersonId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SixDigitHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SixDigitSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("IsOutstandingMarker")
                        .IsUnique();

                    b.ToTable("EnrolmentInvitations");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.EventSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPractice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EventSessions");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.ItemLocationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId", "ProductionLocationId")
                        .IsUnique();

                    b.ToTable("ItemLocationAssignments");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.LocationTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionLocationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReprintCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "ProductionLocationId")
                        .IsUnique();

                    b.ToTable("LocationTickets");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.NumberCounter", b =>
                {
                    b.Property<string>("CounterKind")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterEndpointKey")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("CounterKind", "EventSessionId", "ProductionLocationId", "PrinterEndpointKey");

                    b.ToTable("NumberCounters");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GlobalOrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableLabel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChosenProductionLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocationTicketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitPriceCentsSnapshot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.PrintAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BytesWritten")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrintJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterStatusSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransportDetail")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrintAttempts");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocationTicketId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductionLocationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestedByDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.PrinterConfiguration", b =>
                {
                    b.Property<Guid>("ProductionLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CharactersPerLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePageName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeartbeatSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransportKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductionLocationId");

                    b.ToTable("PrinterConfigurations");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.PrinterStatus", b =>
                {
                    b.Property<Guid>("ProductionLocationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCoverOpen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFaulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInErrorState")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaperEnd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaperNearEnd")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDetail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeardFromAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductionLocationId");

                    b.ToTable("PrinterStatuses");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.ProductionLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlipLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationAccessKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationAccessKey")
                        .IsUnique();

                    b.ToTable("ProductionLocations");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.ServerPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerPeople");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.TableSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TableSuggestions");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.LocationTicket", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.Order", null)
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.OrderLine", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Order", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
