// <auto-generated />
using System;
using GastronomyApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GastronomyApp.Infrastructure.Migrations
{
    [DbContext(typeof(GastronomyAppDbContext))]
    partial class GastronomyAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("GastronomyApp.Core.Entities.CatalogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColourHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("CatalogCategories");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenAlgorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TokenIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenLookupId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TokenSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("TokenLookupId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.EnrolmentInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConsumedByDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IsOutstandingMarker")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("CASE WHEN ConsumedAtUtc IS NULL THEN 1 END", true);

                    b.Property<string>("QrCodeAlgorithm")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("QrCodeHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("QrCodeIterations")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("QrCodeSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("IsOutstandingMarker")
                        .IsUnique();

                    b.ToTable("EnrolmentInvitations");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Festival", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NextOrderNumber")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Festivals");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.FestivalCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("FestivalId", "CatalogItemId")
                        .IsUnique();

                    b.ToTable("FestivalCatalogItems");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.FestivalStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NextStationOrderNumber")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("FestivalId", "StationId")
                        .IsUnique();

                    b.ToTable("FestivalStations");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.ItemStationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId", "CatalogItemId", "StationId")
                        .IsUnique();

                    b.ToTable("ItemStationAssignments");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GlobalOrderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("FestivalId");

                    b.HasIndex("FestivalId", "GlobalOrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChargedPriceCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentNotice")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SettledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SettledByStaffMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StationOrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductionStatus");

                    b.HasIndex("SettledAtUtc");

                    b.HasIndex("StationOrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.OrderItemStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemStatusChanges");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnrolmentInvitationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("EnrolmentInvitationId")
                        .IsUnique();

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnrolmentInvitationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("EnrolmentInvitationId")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.StationOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FestivalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StationOrderNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("OrderId", "StationId")
                        .IsUnique();

                    b.HasIndex("FestivalId", "StationId", "StationOrderNumber")
                        .IsUnique();

                    b.ToTable("StationOrders");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.CatalogItem", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.CatalogCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.FestivalCatalogItem", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastronomyApp.Core.Entities.Festival", null)
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.FestivalStation", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.Festival", null)
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastronomyApp.Core.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Order", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.Festival", null)
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.StationOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("StationOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.OrderItemStatusChange", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.OrderItem", null)
                        .WithMany("StatusChanges")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.StaffMember", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("GastronomyApp.Core.Entities.StaffMember", "DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GastronomyApp.Core.Entities.EnrolmentInvitation", null)
                        .WithOne()
                        .HasForeignKey("GastronomyApp.Core.Entities.StaffMember", "EnrolmentInvitationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Station", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.Device", null)
                        .WithOne()
                        .HasForeignKey("GastronomyApp.Core.Entities.Station", "DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GastronomyApp.Core.Entities.EnrolmentInvitation", null)
                        .WithOne()
                        .HasForeignKey("GastronomyApp.Core.Entities.Station", "EnrolmentInvitationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.StationOrder", b =>
                {
                    b.HasOne("GastronomyApp.Core.Entities.Festival", null)
                        .WithMany()
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GastronomyApp.Core.Entities.Order", null)
                        .WithMany("StationOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastronomyApp.Core.Entities.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.Order", b =>
                {
                    b.Navigation("StationOrders");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.OrderItem", b =>
                {
                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("GastronomyApp.Core.Entities.StationOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
