<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UseAppHost>false</UseAppHost>
        <IsPackable>false</IsPackable>
        <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)\openapi</OpenApiDocumentsDirectory>
        <OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" PrivateAssets="all" IncludeAssets="runtime;build;native;contentfiles;analyzers;buildtransitive"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\GastronomyApp.Api\GastronomyApp.Api.csproj"/>
    </ItemGroup>
</Project>
