<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="ErrorOr"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\GastronomyApp.Contracts\GastronomyApp.Contracts.csproj"/>
    </ItemGroup>
</Project>
