<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UseAppHost>false</UseAppHost>
        <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)\openapi</OpenApiDocumentsDirectory>
        <OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Mapster"/>
        <PackageReference Include="Mapster.DependencyInjection"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" PrivateAssets="all" IncludeAssets="runtime;build;native;contentfiles;analyzers;buildtransitive"/>
        <PackageReference Include="QRCoder"/>
        <PackageReference Include="Serilog.Extensions.Logging"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\GastronomyApp.Contracts\GastronomyApp.Contracts.csproj"/>
        <ProjectReference Include="..\GastronomyApp.Core\GastronomyApp.Core.csproj"/>
        <ProjectReference Include="..\GastronomyApp.Infrastructure\GastronomyApp.Infrastructure.csproj"/>
    </ItemGroup>
</Project>
