<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="QRCoder"/>
        <PackageReference Include="Serilog.Extensions.Logging"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\GastronomyApp.Core\GastronomyApp.Core.csproj"/>
        <ProjectReference Include="..\GastronomyApp.Infrastructure\GastronomyApp.Infrastructure.csproj"/>
    </ItemGroup>
</Project>
